config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root "classrooms#index", as: :authenticated_root
  end
  root 'pages#home'
  resources :classrooms do
    resources :students
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :user
  has_many :students, dependent: :destroy

  validates :subject_name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom

  accepts_nested_attributes_for :classroom

  validates :name, presence: :true
  validates_associated :classroom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :classrooms, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :authenticate_user!
  helper_method :create_groups_of_students

  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find(params[:id])
    @students = @classroom.students.order(:created_at)
    @student = @classroom.students.new
  end
  
  def edit
    @classroom = Classroom.find(params[:id])
  end

  def create
    @user = current_user
    @classroom = @user.classrooms.build(classroom_params)
    if @classroom.save
      redirect_to classrooms_path
    else
      return
    end
  end

  def new
  end
  
  def update
    @classroom = Classroom.find(params[:id])
    students = @classroom.students
    if @classroom.update(classroom_params)
      redirect_to classroom_path(@classroom)
    else
      redirect_to classrooms_path
    end
  end

  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy
    redirect_to classrooms_path
  end

  def create_groups_of_students
    @classroom = Classroom.find(params[:id])
    student_array = @classroom.students.map { |student| student.name }
    new_array = student_array.shuffle.in_groups_of(@classroom.group_size, false)
    new_array
  end

private

  def classroom_params
    params.require(:classroom).permit(:subject_name, :group_size, student_attributes:[:id, :name])
  end

  # def authorized?
  #   @classroom.user == current_user
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def my_classrooms
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def edit
    @classroom = Classroom.find(params[:classroom_id])
    @student = Student.find(params[:id])
  end
  
  def create
    @classroom = Classroom.find(params[:classroom_id])
    @student = @classroom.students.create(student_params)
    redirect_to classroom_path(@classroom)  
  end

  def update
    @classroom = Classroom.find(params[:classroom_id])
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to classroom_path(@classroom)
    end
  end

  def destroy
    @classroom = Classroom.find(params[:classroom_id])
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to classroom_path(@classroom)
  end

private
  def student_params
    params.require(:student).permit(:name, :classroom_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with model: @classroom do |form| %>
  <%= form.label :class_name %>
  <%= form.text_field :subject_name, id: "subject_name" %>
  <%= form.submit %>
<% end %>

app/views/classrooms/edit.html.erb
<%= render 'form' %>
<br>
<%= link_to 'Return to Classroom List', classrooms_path %>

app/views/classrooms/index.html.erb
<%= render 'form' %>
<br>
<table class="table table-hover">
  <tr>
    <th>Class</th>
    <th>Actions</th>
  </tr>
  <% @classrooms.each do |classroom| %>
    <tr>
      <td><%= classroom.subject_name %></td>
      <td><%= link_to "View Students", classroom_path(classroom) %></td>
      <td><%= link_to "Edit Class Name", edit_classroom_path(classroom) %></td>
      <td><%= link_to "Delete Class", classroom_path(classroom),
          method: :delete,
          data: { confirm: "Are you sure? You will be deleting this class and all its students." } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/classrooms/new.html.erb
<% render 'form' %>

app/views/classrooms/show.html.erb
<div class="col-6">
<h2><%= @classroom.subject_name %> Students</h2>
<br>
<%= form_with model: [ @classroom, @classroom.students.build ] do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name,  class: "form-control", placeholder: "Add Student" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<br>

Create Groups

How many students per group?

  <%= form_with model: @classroom do |form| %>
    <%= form.number_field :group_size, id:'group_size' %>
    <%= form.submit %>
  <% end %>

  <br>
  <% create_groups_of_students.each_with_index do |s_array, index| %>
    <%= "Group #{index + 1}. #{s_array.join(', ')}" %>
    <br>
    <br>
  <% end %>


  <table class="table table-hover">
    <tr>  
      <th>Name</th>
      <th>Actions</th>
    </tr>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to "Edit Student", "/classrooms/#{@classroom.id}/students/#{student.id}/edit" %></td>
        <td><%= link_to "Delete Student", "/classrooms/#{@classroom.id}/students/#{student.id}", method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassroomApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render "shared/navigation" %>
    <%= render "shared/flash" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/my_classrooms.html.erb
<h1>Pages#my_classrooms</h1>
<p>Find me in app/views/pages/my_classrooms.html.erb</p>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="container">
        <div class="alert <%= key == 'notice' ? 'alert-primary' : 'alert-danger' %>" role="alert">
            <%= value %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
<!-- app/views/shared/_navigation.html.erb -->
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container">
    <%= link_to "Classroom Groups", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "nav-link") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/students/edit.html.erb
<%= form_with model: [@classroom, @student] do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name,  class: "form-control", placeholder: "Change Student Name" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>

<%= form_with model: @classroom do |form| %> 
  <%= form.collection_check_boxes(:student_ids, @classroom.students, :id, :name) do |builder| %>
    <% unless builder.text == @student.name %>
      <%= builder.label(class: "check_box") { builder.check_box +  builder.text } %>
      <br>
    <% end %>
  <% end %>
   <%= form.submit %>
<% end %>
<br>

app/views/students/index.html.erb
<%= @students.each do |student| %>
<% byebug %>
  <%= student.name %>
  <br>
<% end %>